version: '3.8'
services:
  app:
    build: .
    ports:
      - "3001:3001"
      - "9002:9002"
    volumes:
      - ./userData:/app/userData
    environment:
      - NODE_ENV=production
      - CHROMIUM_PATH=/usr/bin/chromium
    restart: unless-stopped
